/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.socialize;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.proxy.TiViewProxy;

import android.app.Activity;

import com.socialize.Socialize;

@Kroll.module(name="Socialize", id="com.socialize")
public class SocializeModule extends KrollModule
{
	public SocializeModule() {
		super();
	}
	
	@Kroll.method
	public SocializeActionBarViewProxy showActionBar(TiViewProxy parent, String entityKey) {
		return new SocializeActionBarViewProxy(parent, entityKey);
	}
	
	@Override
	public void onDestroy(Activity activity) {
		Socialize.getSocialize().destroy();
		super.onDestroy(activity);
	}

	@Kroll.method
	public void setSocializeCredentials(String consumerKey, String consumerSecret) {
		Socialize.getSocialize().getConfig().setSocializeCredentials(consumerKey, consumerSecret);
	}
	
	@Kroll.method
	public void setFacebookAppId(String appId) {
		Socialize.getSocialize().getConfig().setFacebookAppId(appId);
	}
}
