/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.socialize;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiContext;

import android.app.Activity;

import com.socialize.config.SocializeConfig;
import com.socialize.ui.SocializeUI;

@Kroll.module(name="Socialize", id="com.socialize")
public class SocializeModule extends KrollModule
{
	private String entityKey;
	
	private SocializeActionBarViewProxy actionBar;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;
	
	public SocializeModule(TiContext tiContext) {
		super(tiContext);
	}
	
	@Kroll.method
	public SocializeActionBarViewProxy createActionBar(String entityKey) {
		actionBar = new SocializeActionBarViewProxy(getTiContext(), entityKey);
		return actionBar;
	}
	
	@Override
	public void onDestroy(Activity activity) {
		SocializeUI.getInstance().destroy(activity);
		super.onDestroy(activity);
	}

	@Kroll.getProperty
	public String getEntityKey() {
		return entityKey;
	}

	@Kroll.setProperty
	public void setEntityKey(String entityKey) {
		this.entityKey = entityKey;
	}

	@Kroll.setProperty
	public void setConsumerKey(String consumerKey) {
		Socialize.getSocialize().getConfig().setProperty(SocializeConfig.SOCIALIZE_CONSUMER_KEY, consumerKey);
	}

	@Kroll.setProperty
	public void setConsumerSecret(String consumerSecret) {
		Socialize.getSocialize().getConfig().setProperty(SocializeConfig.SOCIALIZE_CONSUMER_SECRET, consumerSecret);
	}
	
}
